ASR_config: Utils/ASR/config.yml
ASR_path: Utils/ASR/epoch_00100.pth
F0_path: Utils/JDC/bst.t7
batch_size: 5
device: cuda
epochs: 150
fp16_run: true
load_only_params: false
log_dir: Models/VCTK20
loss_params:
  adv_cls_epoch: 50
  con_reg_epoch: 30
  d_loss:
    lambda_adv_cls: 0.1
    lambda_con_reg: 10.0
    lambda_reg: 1.0
  g_loss:
    lambda_adv: 2.0
    lambda_adv_cls: 0.5
    lambda_asr: 10.0
    lambda_cyc: 5.0
    lambda_ds: 1.0
    lambda_f0: 5.0
    lambda_f0_sty: 0.1
    lambda_norm: 1.0
    lambda_sty: 1.0
    norm_bias: 0.5
model_params:
  F0_channel: 256
  dim_in: 64
  latent_dim: 16
  max_conv_dim: 512
  n_repeat: 4
  num_domains: 20
  style_dim: 64
  w_hpf: 0
optimizer_params:
  lr: 0.0001
preprocess_params:
  spect_params:
    hop_length: 300
    n_fft: 2048
    win_length: 1200
  sr: 24000
pretrained_model: ''
save_freq: 2
train_data: Data/train_list.txt
val_data: Data/val_list.txt
